sudo: false
language: node_js
cache:
  directories:
    - $HOME/.cache/yarn
notifications:
  email: false
node_js:
  - '7'
script:
  - yarn prebuild
after_success:
  - if [ -z "$GH_TOKEN" ]; then echo "No credentials, this PR must be from a fork."; travis_terminate 0; fi
  - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ 'CI -' ]]; then travis_terminate 0; fi
  - .travis/after_success_surge.sh